version: '3.9'
services:
  blogdev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: blogdev
    container_name: blogdev
    restart: always
    volumes:
      - .:/opt/blogdev
      - blogDevApp:/opt/blogdev/node_modules
      - blogDevModules:/opt/blogdev/.next
    ports:
      - "80:3000"  
volumes:
  blogDevApp:
    name: 'blogDevApp'
  blogDevModules:
    name: 'blogDevModules'